thank-you-github/thank-you-github

README.md
=> Adding my signature

README.md
more than guys have worked on/at/with github
=> remove gender specific guys

README.md
=> new signature by Jaime Iniesta

README.md
=> Add signature (@nemesiscodex)

README.md
That happens when you try to make changes from your phone lol sorry
=> fix fail markdown

README.md
I believe I fixed a small typo ("in a myriad ways" to "in a myriad ___of___ ways")
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/thank-you-github/thank-you-github/373)
=> I ❤ you GitHub!

README.md
=> Added Kashif Anwaar (my) sign

README.md
Thank you for listening, Github!
=> Added self signature

README.md
=> Thank you Github

README.md
=> Add my sign

README.md
=> Add signature of Zev Fu

README.md
=> Thank you Github!

README.md
=> Thanks guys

README.md
=> @vasanthaganeshk signed the repo!

README.md
=> new signature by Simon Grim

README.md
Hi,
Am glad to the part of the chain of appreciation to Github.
Thanks Github.
=> progzilla signed the letter

README.md
=> Vuong Nguyen signed

README.md
Thank you Github. :kissing_heart: Have an Octotastic day! :smile_cat:
=> Thank you Github :kissing_cat:

README.md
=> Signed the letter

README.md
=> Adding myself to the README.md file.

README.md
Added name to the Signed list.
=> Thank You GitHub from @faheemzunjani

README.md
Thanks from [@BrandonHe](https://github.com/brandonhe)
=> update REAME.md to add new signature by BrandonHe

README.md
Just wanted to sign as well.
Thanks!
=> Sign Commit

README.md
=> Added self to list

README.md
=> New signature by @sachin21

README.md
=> New signature by @shixinzhang

README.md
Thanks for the great repo. Please add my signature to the list.
=> New signature by @mightyCrow

README.md
=> Add myself :P

README.md
=> Add malayaleecoder

README.md
=> fix  country

README.md
=> add @clarkzjw

README.md
Hi! Please pull my commit, so I can also have a chance to thank github.
=> New Signature by Priyank Agarwal(#580)

README.md
Returning my original user name, this was changed on #557.
_- cheers_
=> Update my Github username

README.md
=> Signature by Vipin Madhavanunni

README.md
I have added my name. It would be great if you could add me.
=> Add @chamow97

README.md
My name along with id has been added twice, i have removed duplicate one and kept the latest entry.
=> duplicate entry removed

README.md
Some spacing errors have been removed.
=> Fixed some markdown typos

README.md
Hi!
We're @Kottans and it's a community of developers (mostly from Ukraine), we love to code and help each other. Also, we teach programming for free and have several offline courses.
We love GitHub and think that it is the best that could happen with an OSS ❤️ 
After an internal discussion, we decided to add org's sign here.
If you want to learn more about @Kottans, please, check these links: 
[Here](http://kottans.org) you can find our website, [materials & projects](https://github.com/Kottans), [our ongoing courses/events](https://github.com/Kottans/kottans-ongoing-projects/issues?q=is%3Aopen+is%3Aissue) and a [course bootstrap](https://github.com/Kottans/kottans-course-bootstrap).
=> @Kottans sign

README.md
please remove double occurence, thank you!
=> remove double please

README.md
Please read and remove:
Practically all PRs are non-mergeable because they conflict with each other, and
continually asking for rebases would be impractical.
Because of that, it is likely that your signature is added via a commit that
references and closes the PR, rather than a regular merge. I have a supervised
script that processes the patches and commits them individually, referencing
their origin PR for credit and authenticity. In such case, you'll see said
commit linked in the notification email and in the page of the PR itself.
=> Updated oddball with country.

README.md
=> Signed by creyD

README.md
I deleted the repository for organizing the commit and forked it again.
=> Fix signature

README.md
and the whole readme.md ended up indented like a code block. I'm fixing it
=> Something happened

README.md
Thanks for creating & maintaining this 👍
=> New signature

README.md
Reverts thank-you-github/thank-you-github#2497. @TheDevMinerTV check for syntax error
=> Revert "Add myself"

README.md
=> Update Job Title for Khurshid Fayzullaev

README.md
Thanks for your signature. Make sure the following rules are correctly followed.
* Please add your signature at the end of the list, at the bottom.
* Just one line, following the pattern you can see in the existing ones.
* Make sure the linked username in the signature matches exactly the GitHub handler of the account that opens the PR. This is the way to ensure the signature belongs to who has written the patch.
PS: I hope that I've fixed the Syntax error.
=> Add my own signature

.github/CONTRIBUTING.md
Fixes minor typo within contributing guide.
=> [docs]: fix minor typo

README.md
Thanks for your signature. Make sure the following rules are correctly followed.
* Please add your signature at the end of the list, at the bottom.
* Just one line, following the pattern you can see in the existing ones.
* Make sure the linked username in the signature matches exactly the GitHub handler of the account that opens the PR. This is the way to ensure the signature belongs to who has written the patch.
=> add signature from Lu Dinh Hai

README.md
Thanks for your signature. Make sure the following rules are correctly followed.
* Please add your signature at the end of the list, at the bottom.
* Just one line, following the pattern you can see in the existing ones.
* Make sure the linked username in the signature matches exactly the GitHub handler of the account that opens the PR. This is the way to ensure the signature belongs to who has written the patch.
=> Update henry to repo again:

README.md
Thanks for your signature. Make sure the following rules are correctly followed.
* Please add your  at the end of the list, at the bottom.
* Just one line, following the pattern you can see in the existing ones.
* Make sure the linked username in the signature matches exactly the GitHub handler of the account that opens the PR. This is the way to ensure the signature belongs to who has written the patch.
=> Add Lakshay Wadhwa details

README.md
=> Apended thanks from Jovial

README.md
=> Changed work

README.md
Please remove me from this list. Thanks!
=> Remove myself from the signatures list
